# Generated by Django 3.1.5 on 2021-01-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualqueueapi', '0004_auto_20210123_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(default='name_value', max_length=60),
            preserve_default=False,
        ),
    ]
