# Generated by Django 3.1.5 on 2021-01-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualqueueapi', '0007_auto_20210123_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
